### ISSUE TITLE
Irrational pH values from the `fierer` resource

### ISSUE THREAD

**Issue by hariszaf** [bacteria-archaea-traits/bacteria-archaea-traits#1]
Hi there :wave: 

First of all, congrats for this project! 
Really useful work! 

By running:
```bash
awk -F"," '$24!="NA" && $24 ~ /[A-z]/ {print $24 "\t~~\t" $3}' condensed_traits_GTDB.csv 
```

I  noticed that there some cases where you get values such as `threonine`, `soil` and other non numeric values. 

I also noticed that all these cases (`n=746`) have as `data_source:fierer`.
You are mentioning on the corresponding [`README.md`](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/tree/master/data/raw/fierer) that there is an issue with this resource and you have a chunck of code but i am not sure if i should run it or not. 

Could you please make this clear ? 

Thanks a lot !

**Comment by Brunokemon** [comment]
From what I checked the corrections are already being made on the fly, so you don't need to run that code yourself. 

And the following comment was added to the README.md:
_*Do not run this code again, because it will overwrite the datafile, in which I added the missing accessions numbers._

**Comment by hariszaf** [comment]
Hi @Brunokemon 
Thanks a lot for the reply. I guess the issue is now addressed. :smiley:
