### ISSUE TITLE
Intracellular trait

### ISSUE THREAD

**Issue by BrunoKVI** [bacteria-archaea-traits/bacteria-archaea-traits#2]
Hi

Firstly marvelous job. That was something really needed and important.

Now for the question, your readme says about an intracellularity field in the data.
I searched the condensed files but couldn't find it.
Can you indicate where to find that field?

**Comment by danielaagrennielsen** [comment]
Hi there, 

Thank you for the supportive comment!

As for the intracellular field; this field was not included in the condensation of the files for publication. Apologies if this is not clear in the readme description. 

However, the means to include it is within the code. Within the folder "conversion_tables" there is a csv file ("intracellular_organisms.csv") with the list of organisms (at different phyolgentic levels) that we have classified as being intracellular. I should mention the list is of course by no means exhaustive. 

In the condense_species.R file you can find the code for implementing this data at line 444 (commented out). You do not have to run the whole script. Simply load the condensed data frame (in the code named df_final) and then run this bit of code to create the 'intracellular' column. 

I hope this helps.

Cheers, 
Daniel

**Comment by BrunoKVI** [comment]
Thank you! 
I'll do that.
