### ISSUE TITLE
bacdive-microa, fierer, pasteur, nielsen, & silva preparation issues

### ISSUE THREAD

**Issue by lbrazell** [bacteria-archaea-traits/bacteria-archaea-traits#5]
I've followed the instructions detailed in the workflow.R documentation and have encountered the following errors for the bacdive-microa, fierer, pasteur, nielsen & silva dbs. I have removed the db's from the settings.R file and can access the remaining merge/condense steps, but would like to have these db's included in the updated bacteria/archaea trait lists. I did add the relationship="many-to-many" option in the left_join statements but that didn't do anything to help. Any help would be greatly appreciated, and looking forward to using your tool to get the most recent dbs! Thank you.

```
[1] "Processing data-set: **bacdive-microa**..."
Error in gsub("\"", "", bac) : input string 2610 is invalid
In addition: Warning messages:
1: In left_join(., sp, by = c(name = "short")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 283 of `x` matches multiple rows in `y`.
ℹ Row 113 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
2: In gsub("\"", "", bac) :
  unable to translate '"6771";"CCUG 45921, DSM 19152, ATCC 700512, CIP 106632";"Legionella beliardensis";"Montb<e9>liard A1";"Legionella beliardensis";"20215";' to a wide string

```
```
[2] "Processing data-set: fierer..."
Error in gsub(",", "", fie$rRNA16S) : input string 2113 is invalid
In addition: Warning messages:
1: In left_join(., sp, by = c(name = "short")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 283 of `x` matches multiple rows in `y`.
ℹ Row 113 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
2: In gsub(",", "", fie$rRNA16S) :
  unable to translate 'B326358_<d1><d0>' to a wide string
```

```
[3] "Processing data-set: pasteur..."
New names:
• `` -> `...6`
• `` -> `...8`
• `Sequence reference` -> `Sequence reference...14`
• `Sequence reference` -> `Sequence reference...28`
Rows: 13201 Columns: 33
Error in nchar(x, "width") : invalid multibyte string, element 1
In addition: There were 18 warnings (use warnings() to see them)

```
```
[4] "Processing data-set: nielsen..."
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
In addition: There were 16 warnings (use warnings() to see them)
```

```
[5] "Processing data-set: silva..."
Error in gsub("^.*?\\.", "", sil_refs$full_text) :
  input string 92 is invalid
In addition: There were 50 or more warnings (use warnings() to see the first 50)


```

**Comment by danielaagrennielsen** [comment]
Hello Ibrazell, 

Thanks for reaching out - I hope I can be of some assistance. 

Firstly, there should be no need for many-many relationship joins, so please avoid this. Rather, I recommend you take a look at the specific rows mentioned in the error outputs and see if there are formatting issues that could be resolved before running the script. Formatting issues can come about in many ways, even simply by opening and saving a data-set in software like Excel. 

When you use new data sets it is not unlikely you will run in to new formatting issues (user input is full of errors), so you will have to handle such by modifying the code to deal with specific issues. There are plenty of examples of this in the existing code.

More specific comments:

In [1] I suggest you check for formatting issues in line 2610 of the specific dataset (that makes the gsub fail when trying to remove backslashes) and see if you can resolve this. Similarly, I would check lines 113 and 283 to see why they seem to result in many-many relationships when joined. If the issues cannot be resolved, you could consider simply removing the specific rows from the dataset and see if that resolves the issues.

The same answer goes for [2] - in both cases I can see some code in the problematic string that contains brackets "<>" - this is likely to break a regex call. See if removing these would help.

In [3] you seem to have an issue with extra columns in the data set - these are named automatically by the script and may affect the outcome. There should be no unnamed rows in the datasets. I suggest you check the data file for extra unnamed rows and remove them or fix any issues with naming. Also, check row 13201 column 33, the content of this field seem to break the nchar() call. Does the content look funny? Can it be fixed or should it just be deleted? 

In [4] it seems the dataset nielsen... isn't located where the code expects to find it. Check if the file name is correct and that the file to the path is correct (compared to the code). 

In [5] you need to check line 92 in the full_text column and correct any issues that makes the gsub script fail.

Kind regards, 
Daniel

**Comment by lbrazell** [comment]
Hello Daniel!

Thanks very much for your help with this; your instructions were able to help me figure out where the issues were so that I could fix them and move forward! I have only one more outstanding question and that is about the Fierer database. I modified the offending lines (they contained special unicode characters), however, I'm still getting the following error:

`[1] "Processing data-set: fierer..."
Error in gsub("_\xd1\xd0", "-", fie$Width) : 'pattern' is invalid
In addition: Warning messages:
1: In eval(ei, envir) : NAs introduced by coercion
2: In eval(ei, envir) : NAs introduced by coercion
3: In eval(ei, envir) : NAs introduced by coercion
4: In gsub("_\xd1\xd0", "-", fie$Width) :
  unable to translate '_<d1><d0>' to a wide string`

I'm not entirely sure how to overcome this error- I have removed out and modified all of the special characters but this error still persists and doesn't give me a specific line where it's occurring. Do you have any suggestions for this error? Once I get this fixed we will be able to use your tool and are looking forward to it!

Many thanks,

Lauren

**Comment by danielaagrennielsen** [comment]
Hi Lauren, 

Glad to hear my comments helped! 

As for the remaining issue, this bit of code is trying to remove the bit of string ""_\xd1\xd0" in a data field in the "Width" column of the "fie" data frame. Clearly, the search pattern in gsub (which is supposed to exchange the problematic string with 'nothing') no longer works. Why this would change from previous I don't know. The best solution solution would be to find out how to correct the bit of regex code so that it can correctly locate the particular string (perhaps needing to escape the underscore using a double backslash would work; like this "\\_\xd1\xd0". Unfortunately, I am not an expert on regex coding. 

Alternatively, running the processing script for the Fierer dataset, you could search for the specific data field in the data frame either manually by simply sorting the "Width" column in the "fie" data frame to find out which row the problematic code is in and then simply insert a line of code in the script (replacing the original gsub code) that deletes the data in that field using something like: fie[x, "Width"] <- NA, where x is the row number where the issue is located. Of course that would mean you loose that data point, but such is life!

Edit: I just realised you mentioned that you have removed all special characters already. So above does't really apply. The problem is the search pattern in the gsub itself - not the presence of the characters in the data (because you have already removed them). You can simply comment out the gsub using a hashtag so it doesn't run! 

Hope this helps!

Cheers, 
Daniel

**Comment by lbrazell** [comment]
Hi Daniel!

That worked- I had to comment out the gsub lines for length and width in that area (commenting out only width gave the same error, only with length). I think that this is removing lines that are needed to make a temporary file, and I get this error message:

`Error in `$<-.data.frame`(`*tmp*`, d1, value = character(0)) :
  replacement has 0 rows, data has 5103
In addition: Warning messages:
1: In eval(ei, envir) : NAs introduced by coercion
2: In eval(ei, envir) : NAs introduced by coercion
3: In eval(ei, envir) : NAs introduced by coercion`

I hate to keep bugging you with this, but appreciate all the help you've given me thus far. 

Best,

Lauren

**Comment by danielaagrennielsen** [comment]
Hi Lauren,

Apologies for the late reply, I am currently on a research vessel heading
towards the southern ocean and will not be online much over the next month.

I'm not quite following how you got the last error message - and the error
message isn't telling me much. Perhaps if you could send me the code with
comments highlighting your edits I might be able to see what is happening.

Again, I apologize if my responses are a little slow.

Best,
Daniel

**Comment by lbrazell** [comment]
Hello Daniel!

Thanks so much for your reply and please do not apologize- enjoy your time at sea and accept my sincere appreciation for your time and attention in helping me.

I've removed all of the special unicode characters from the files in the /raw/fierer/ directory. On line 150 and 151 of the /preparation/fierer.R file, I have commented out the problematic gsub lines for fie$Length and fie$Width; please see below:
![image](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/assets/137530283/1efee062-ebbf-45f0-baeb-2cb7772b9126)

After updating the functions.R and settings.R in the R environment and running the preparation script for only the Fierer db, below is the error message that I get:
![image](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/assets/137530283/b6f4ad11-4cd5-4482-8c08-142554c92ab1)

I think that removing the gsub lines is creating this issue where an empty temporary file is being created. What do you think?

Again I appreciate your help and hope all is well on the open ocean! 

Best,

LRB

**Comment by danielaagrennielsen** [comment]
Hi Lauren,

Unfortunately, the error output doesn't give me enough to find out where
the problem arises.

I suggest that you run the fierer code manually - running a few lines or
one chunk of code at the time (from top down), until the error appears. We
need to know exactly which line causes it and what comes before. This
should tell us what the error relates to. Hopefully, we can then sort it
out. Commenting out the gsub bits above shouldn't break the code if the
special characters etc., have been removed already. So let's have a closer
look.

If that doesn't work, I suggest you send me your fierer data file (with
your edits) as well as your fierer.R code and I can see if I can make it
work locally. I don't think the fierer data file is very big, so I should
be able to receive it here.

Kind regards,
Daniel

**Comment by lbrazell** [comment]
Hi Daniel,

Hope all is well on the open ocean!

I will look into this, however, in the meantime, I do want to give you access to the files that I've been working with. Please see attached folder containing the files that you need!

Best,

Lauren
[fierer.R.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938797/fierer.R.gz)
[README.txt.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938798/README.txt.gz)
[Fierer author proof 2.pdf.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938799/Fierer.author.proof.2.pdf.gz)
[ijsem_05_05_15_clean.txt.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938800/ijsem_05_05_15_clean.txt.gz)
[ijsem_05_05_15_clean_fixed.csv.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938801/ijsem_05_05_15_clean_fixed.csv.gz)
[IJSEM_pheno_db_v1.0.csv.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938802/IJSEM_pheno_db_v1.0.csv.gz)
[IJSEM_pheno_db_v1.0.txt.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938803/IJSEM_pheno_db_v1.0.txt.gz)
[README.md.gz](https://github.com/bacteria-archaea-traits/bacteria-archaea-traits/files/14938804/README.md.gz)

**Comment by danielaagrennielsen** [comment]
Hi Lauren,

Thanks for sending that through - it helped.

The last error message you sent through arises because there are no columns
d1 and d2 in your data frame. These columns were created i the step you
commented out due to bad regex expressions: fie$d1 <- gsub("_\xd1\xd0",
"-", fie$Width)
Notice how fie$Width is used to create fie$d1 while substituting
problematic characters.

So, to fix this we simply need to create the d1 and d2 columns manually
after above, like this:

fie$d1 <- fie$Width
fie$d2 <- fie$Length

That should allow the code to run from there.

Hope it helps!
Daniel

**Comment by lbrazell** [comment]
Hi Daniel!

That worked perfectly, thank you so much for your help on this. We've got the DB and are ready to use it!

All the best,

Lauren

**Comment by danielaagrennielsen** [comment]
Hi Lauren,

Glad to hear it, and no problems!
Good luck with it all.

Cheers,
Daniel
